name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Forge build and Test
        run: |
          forge build
          forge test
      - name: Check contract sizes
        run: |
          forge build --sizes
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.8
      - name: Hardhat compile
        run: |
          npm install
          npx hardhat compile
      - name: Hardhat test local
        env:
          FORKING: false
        run: |
          npx hardhat test --network hardhat
      - name: Deployment script test
        run: |
          npm install
          node scripts/hardhat/deploy.js -T -t a:8 b:9 -n hardhat -- a:WETH
